using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ShellExtension.Formats.LIS
{
    public class LISMnemonicsLib
    {
        public static Dictionary<string, string> LISMnemonics = new Dictionary<string, string>()
        {
            { "5БК_Напряжение", "5BKU"},
            { "5БК_Номер", "5NUM"},
            { "5БК_Температура", "5TM"},
            { "5БК_Режим ", "5MOD"},
            { "5БК_I_Anoise ", "5IAN"},
            { "5БК_I_Inoise", "5IIN"},
            { "5БК_I_Rnoise", "5IRN"},
            { "5БК_I_Snoise", "5ISN"},
            { "5БК_Unny_Anoise ", "5UNA"},
            { "5БК_Unny_Inoise ", "5UNI"},
            { "5БК_Unny_Rnoise ", "5UNR"},
            { "5БК_Umn_Anoise", "5UMA"},
            { "5БК_Umn_Inoise ", "5UMI"},
            { "5БК_Umn_Rnoise ", "5UMR"},
            { "5БК_U_Snoise ", "5USN"},
            { "5БК_I_Aa0a2", "IA02"},
            { "5БК_I_Ia0a2", "II02"},
            { "5БК_I_Ra0a2 ", "IR02"},
            { "5БК_I_Sa0a2", "IS02"},
            { "5БК_Unny_Aa0a2", "NA02"},
            { "5БК_Unny_Ia0a2", "NI02"},
            { "5БК_Unny_Ra0a2", "NR02"},
            { "5БК_Umn_Aa0a2", "MA02"},
            { "5БК_Umn_Ia0a2", "MI02"},
            { "5БК_Umn_Ra0a2", "MR02"},
            { "5БК_U_Sa0a2", "US02"},
            { "5БК_I_Aa1a2", "IA12"},
            { "5БК_I_Ia1a2", "II12"},
            { "5БК_I_Ra1a2", "IR12"},
            { "5БК_I_Sa1a2", "IS12"},
            { "5БК_Unny_Aa1a2", "NA12"},
            { "5БК_Unny_Ia1a2", "NI12"},
            { "5БК_Unny_Ra1a2", "NR12"},
            { "5БК_Umn_Aa1a2", "MA12"},
            { "5БК_Umn_Ia1a2", "MI12"},
            { "5БК_Umn_Ra1a2", "MR12"},
            { "5БК_U_Sa1a2", "US12"},
            { "5БК_I_Aa2a3", "IA23"},
            { "5БК_I_Ia2a3", "II23"},
            { "5БК_I_Ra2a3", "IR23"},
            { "5БК_I_Sa2a3", "IS23"},
            { "5БК_Unny_Aa2a3", "NA23"},
            { "5БК_Unny_Ia2a3", "NI23"},
            { "5БК_Unny_Ra2a3", "NR23"},
            { "5БК_Umn_Aa2a3", "MA23"},
            { "5БК_Umn_Ia2a3", "MI23"},
            { "5БК_Umn_Ra2a3", "MR23"},
            { "5БК_U_Sa2a3", "US23"},
            { "5БК_I_Aa3a4", "IA34"},
            { "5БК_I_Ia3a4", "II34"},
            { "5БК_I_Ra3a4", "IR34"},
            { "5БК_I_Sa3a4", "IS34"},
            { "5БК_Unny_Aa3a4", "NA34"},
            { "5БК_Unny_Ia3a4", "NI34"},
            { "5БК_Unny_Ra3a4", "NR34"},
            { "5БК_Umn_Aa3a4", "MA34"},
            { "5БК_Umn_Ia3a4", "MI34"},
            { "5БК_Umn_Ra3a4", "MR34"},
            { "5БК_U_Sa3a4", "US34"},
            { "5БК_I_Aa4a5", "IA45"},
            { "5БК_I_Ia4a5", "II45"},
            { "5БК_I_Ra4a5", "IR45"},
            { "5БК_I_Sa4a5", "IS45"},
            { "5БК_Unny_Aa4a5", "NA45"},
            { "5БК_Unny_Ia4a5", "NI45"},
            { "5БК_Unny_Ra4a5", "NR45"},
            { "5БК_Umn_Aa4a5", "MA45"},
            { "5БК_Umn_Ia4a5", "MI45"},
            { "5БК_Umn_Ra4a5", "MR45"},
            { "5БК_U_Sa4a5", "US45"},
            { "5БК_I_Aa5a6", "IA56"},
            { "5БК_I_Ia5a6", "II56"},
            { "5БК_I_Ra5a6", "IR56"},
            { "5БК_I_Sa5a6", "IS56"},
            { "5БК_Unny_Aa5a6", "NA56"},
            { "5БК_Unny_Ia5a6", "NI56"},
            { "5БК_Unny_Ra5a6", "NR56"},
            { "5БК_Umn_Aa5a6", "MA56"},
            { "5БК_Umn_Ia5a6", "MI56"},
            { "5БК_Umn_Ra5a6", "MR56"},
            { "5БК_U_Sa5a6", "US56"},
            { "5БК_R5", "BKR5"},
            { "5БК_R4", "BKR4"},
            { "5БК_R3", "BKR3"},
            { "5БК_R2", "BKR2"},
            { "5БК_R1", "BKR1"},
            { "5БК_FFocusing", "FFOC"},
            { "5БК_FUmn_Aa5a6", "FU56"},
            { "5БК_FUmn_Aa4a5", "FU45"},
            { "5БК_FUmn_Aa3a4", "FU34"},
            { "5БК_FUmn_Aa2a3", "FU23"},
            { "5БК_FUmn_Aa1a2", "FU12"},
            { "5БК_FR5", "FR5"},
            { "5БК_FR4", "FR4"},
            { "5БК_FR3", "FR3"},
            { "5БК_FR2", "FR2"},
            { "5БК_FR1", "FR1"},
            { "5ik_05", "IR05"},
            { "5ik_07", "IR07"},
            { "5ik_10", "IR10"},
            { "5ik_13", "IR13"},
            { "5ik_16", "IR16"},
            { "5ik_ps", "SP"},
            { "5ik_t_pic16", "TP16"},
            { "5ik_t_pic33", "TP33"},
            { "5ik_error", "IKER"},
            { "Идентификатор ", "ID"},
            { "Усиление", "GAIN"},
            { "Wave1", "W1"},
            { "Wave2", "W2"},
            { "Wave1_КУ2", "W1K2"},
            { "Wave2_КУ2", "W2K2"},
            { "Wave1_KU2", "W1K2"},
            { "Wave2_KU2", "W2K2"},
            { "Wave1_F1_KU1", "W111"},
            { "Wave2_F1_KU1", "W211"},
            { "Wave1_F1_KU2", "W112"},
            { "Wave2_F1_KU2", "W212"},
            { "Wave1_F2_KU1", "W121"},
            { "Wave2_F2_KU1", "W221"},
            { "Wave1_F2_KU2", "W122"},
            { "Wave2_F2_KU2", "W222"},
            { "Wave1_F3_KU1", "W131"},
            { "Wave2_F3_KU1", "W231"},
            { "Wave1_F3_KU2", "W132"},
            { "Wave2_F3_KU2", "W232"},
            { "Wave1_F4_KU1", "W141"},
            { "Wave2_F4_KU1", "W241"},
            { "Wave1_F4_KU2", "W142"},
            { "Wave2_F4_KU2", "W242"},
            { "parameters", "PAR"},
            { "Wave3", "W3"},
            { "Wave4", "W4"},
            { "k_aksh_num_vk", "NUMV"},
            { "ВИКИЗ-Н-ПС_код", "SPCO"},
            { "ВИКИЗ-Н-dFi1_код", "FI1C"},
            { "ВИКИЗ-Н-dFi2_код", "FI2C"},
            { "ВИКИЗ-Н-dFi3_код", "FI3C"},
            { "ВИКИЗ-Н-dFi4_код", "FI4C"},
            { "ВИКИЗ-Н-dFi5_код", "FI5C"},
            { "ВИКИЗ-Н-ПС", "SPVI"},
            { "ВИКИЗ-Н-dFi1", "DFI1"},
            { "ВИКИЗ-Н-dFi2", "DFI2"},
            { "ВИКИЗ-Н-dFi3", "DFI3"},
            { "ВИКИЗ-Н-dFi4", "DFI4"},
            { "ВИКИЗ-Н-dFi5", "DFI5"},
            { "ggklp_stab_mz", "NSTB"},
            { "ggklp_stab_bz", "LSTB"},
            { "ggklp_tau_mz", "NTAU"},
            { "ggklp_tau_bz", "FTAU"},
            { "ggklp_gain_mz", "RNGN"},
            { "ggklp_gain_bz", "RFGN"},
            { "ggklp_autogain_mz", "RNGA"},
            { "ggklp_autogain_bz", "RFGA"},
            { "ggklp_temp", "DTEM"},
            { "ggklp_u1", "DSU1"},
            { "ggklp_u_motor", "DSMC"},
            { "ggklp_i_motor", "DSMV"},
            { "ggklp_z", "DSZ"},
            { "ggklp_d1", "DSD1"},
            { "ggklp_d2", "DSD2"},
            { "ggklp_stat", "DSST"},
            { "ggklp_t", "DST"},
            { "ggklp_mz_int", "RNIN"},
            { "ggklp_mz1", "DRN1"},
            { "ggklp_mz2", "DRN2"},
            { "ggklp_mz", "DCRN"},
            { "ggklp_mz_rep", "NREP"},
            { "ggklp_bz_int", "RLIN"},
            { "ggklp_bz", "DCRF"},
            { "ggklp_bz_rep", "LREP"},
            { "ГГК-ЛП-Плотность МЗ", "DRN"},
            { "ГГК-ЛП-Плотность БЗ", "DRL"},
            { "ГГК-ЛП-dПлотность", "COR"},
            { "ГГК-ЛП-Плотность", "DEN"},
            { "ГГК-ЛП-Z", "EAN"},
            { "ГГК-ЛП-Pe", "PEF"},
            { "spectr mz", "SPRN"},
            { "spectr bz", "SPRL"},
            { "ГГЦ-Номер", "GNUM"},
            { "ГГЦ-БЗ1", "L1CO"},
            { "ГГЦ-БЗ1 уе", "L1UE"},
            { "ГГЦ-БЗ2", "L2CO"},
            { "ГГЦ-БЗ2 уе", "L2UE"},
            { "ГГЦ-БЗ3", "L3CO"},
            { "ГГЦ-БЗ3 уе", "L3UE"},
            { "ГГЦ-МЗ-0500", "N050"},
            { "ГГЦ-БЗ4 уе", "L4UE"},
            { "ГГЦ-МЗ-1000", "N100"},
            { "ГГЦ-БЗ5 уе", "L5UE"},
            { "ГГЦ-МЗ-1500", "N150"},
            { "ГГЦ-БЗ6 уе", "L6UE"},
            { "ГГЦ-МЗ-2000", "N200"},
            { "ГГЦ-БЗ7 уе", "L7UE"},
            { "ГГЦ-МЗ-3000", "N300"},
            { "ГГЦ-БЗ8 уе", "L8UE"},
            { "ГГЦ-БЗ инт", "LIN"},
            { "ГГЦ-БЗ инт уе", "LUE"},
            { "ГГЦ-МЗ", "NCO"},
            { "ГГЦ-МЗ уе", "NUE"},
            { "ГГЦ-ГК", "GR"},
            { "ГГЦ-Угол", "ANG"},
            { "ГГЦ-Температура", "TEMP"},
            { "ГГЦ-Напряжение зонда", "USON"},
            { "ГГЦ-Счетчик 50мс", "CNT5"},
            { "ГГЦ-Цикл. счетчик", "CNT"},
            { "ГГЦ-БЗ4", "L4CO"},
            { "ГГЦ-БЗ5", "L5CO"},
            { "ГГЦ-БЗ6", "L6CO"},
            { "ГГЦ-БЗ7", "L7CO"},
            { "ГГЦ-БЗ8", "L8CO"},
            { "ЛМ_Ku1", "LMK1"},
            { "ЛМ_Ku2", "LMK2"},
            { "ЛМ_Ku_dif", "LDIF"},
            { "ЛМ_sdvig", "LSDV"},
            { "ЛМ_time", "LTIM"},
            { "ЛМ_LM", "CCL"},
            { "ЛМ_T1", "LM1"},
            { "ЛМ_T2", "LM2"},
            { "ЛМ_T3", "LM3"},
            { "ЛМ_T4", "LM4"},
            { "ЛМ_T5", "LM5"},
            { "ЛМ_T6", "LM6"},
            { "ЛМ_T7", "LM7"},
            { "ЛМ_T8", "LM8"},
            { "ЛМ_T9", "LM9"},
            { "ЛМ_T10", "LM10"},
            { "ГК_Uhv", "GRHV"},
            { "ГК_Upd_gk", "GRPD"},
            { "ГК_T", "GRTM"},
            { "ГК_gk", "GRC"},
            { "ГК-ГК_мкР", "GR"},
            { "Т внутр.", "TMIN"},
            { "ГК - ГК_мкР", "GR"},
            { "Давление скв.", "PRES"},
            { "Темп. скв.", "TM"},
            { "Канал давления ДД", "PDD"},
            { "Канал температуры ДД", "TDD"},
            { "Канал температуры PTC", "TRTS"},
            { "ЛМ_T11", "LM11"},
            { "ЛМ_T12", "LM12"},
            { "ЛМ_T13", "LM13"},
            { "ЛМ_T14", "LM14"},
            { "ЛМ_T15", "LM15"},
            { "ЛМ_T16", "LM16"},
            { "ЛМ_T17", "LM17"},
            { "ЛМ_T18", "LM18"},
            { "ЛМ_T19", "LM19"},
            { "ЛМ_T20", "LM20"},
            { "ЛМ1_T1", "LT1"},
            { "ЛМ1_T2", "LT2"},
            { "ЛМ1_T3", "LT3"},
            { "ЛМ1_T4", "LT4"},
            { "ЛМ1_T5", "LT5"},
            { "ЛМ1_T6", "LT6"},
            { "ЛМ1_T7", "LT7"},
            { "ЛМ1_T8", "LT8"},
            { "ЛМ1_T9", "LT9"},
            { "ЛМ1_T10", "LT10"},
            { "ЛМ1_T11", "LT11"},
            { "ЛМ1_T12", "LT12"},
            { "ЛМ1_T13", "LT13"},
            { "ЛМ1_T14", "LT14"},
            { "ЛМ1_T15", "LT15"},
            { "ЛМ1_T16", "LT16"},
            { "ЛМ1_T17", "LT17"},
            { "ЛМ1_T18", "LT18"},
            { "ЛМ1_T19", "LT19"},
            { "ЛМ1_T20", "LT20"},
            { "ЛМ2_T1", "L21"},
            { "ЛМ2_T2", "L22"},
            { "ЛМ2_T3", "L23"},
            { "ЛМ2_T4", "L24"},
            { "ЛМ2_T5", "L25"},
            { "ЛМ2_T6", "L26"},
            { "ЛМ2_T7", "L27"},
            { "ЛМ2_T8", "L28"},
            { "ЛМ2_T9", "L29"},
            { "ЛМ2_T10", "L210"},
            { "ЛМ2_T11", "L211"},
            { "ЛМ2_T12", "L212"},
            { "ЛМ2_T13", "L213"},
            { "ЛМ2_T14", "L214"},
            { "ЛМ2_T15", "L215"},
            { "ЛМ2_T16", "L216"},
            { "ЛМ2_T17", "L217"},
            { "ЛМ2_T18", "L218"},
            { "ЛМ2_T19", "L219"},
            { "ЛМ2_T20", "L220"},
            { "Spectr1", "SP1"},
            { "Spectr2", "SP2"},
            { "ИН - Натяжение", "TENS"},
            { "ИН - Температура_вн", "TMIN"},
            { "ИН _Термометр", "TM"},
            { "ИН - Рез_М1", "RES1"},
            { "ИН - Рез_М2", "RES2"},
            { "ИН - Рез", "RES"},
            { "inkl_U_GK", "GRHV"},
            { "inkl_Pd_GK", "GRPD"},
            { "inkl_gk_imp", "GRC"},
            { "inkl_gk", "GR"},
            { "inkl_time", "INTI"},
            { "inkl_zenit", "ZEN"},
            { "inkl_vizir", "VIZ"},
            { "inkl_vizir_mag", "VIZM"},
            { "inkl_azimut", "AZI"},
            { "inkl_mag_pole", "MPOL"},
            { "inkl_grav_pole", "GPOL"},
            { "inkl_mag_naklon", "MINC"},
            { "inkl_Tax", "TAX"},
            { "inkl_Tmag", "TMAG"},
            { "inkl_Gx", "GX"},
            { "inkl_Gy", "GY"},
            { "inkl_Gz", "GZ"},
            { "inkl_Mx", "MX"},
            { "inkl_My", "MY"},
            { "inkl_Mz", "MZ"},
            { "inkl_Ax", "AX"},
            { "inkl_Ay", "AY"},
            { "inkl_Az", "AZ"},
            { "inkl_At", "AT"},
            { "inkl_AMx", "AMX"},
            { "inkl_AMy", "AMY"},
            { "inkl_AMz", "AMZ"},
            { "inkl S_NUM_GK", "GRNU"},
            { "inkl S_NUM_INKL", "INNU"},
            { "ИНКЛ_Зенит", "ZEN"},
            { "ИНКЛ_Визир", "VIZ"},
            { "ИНКЛ_Азимут", "AZI"},
            { "ИНКЛ_Магн_накл", "MINC"},
            { "ИНКЛ_Напр_м_поля ", "MPOL"},
            { "ИНКЛ_Вектор_СТ", "GRAV"},
            { "ИНКЛ_Ориент", "ORIT"},
            { "ИНКЛ_Темп", "TMIN"},
            { "ИНКЛ_ГК", "GR"},
            { "2ННК_Uhv_nnkt", "NCHV"},
            { "2ННК_Upd_bz", "RFPD"},
            { "2ННК_Upd_mz", "RNPD"},
            { "2ННК_T", "NCTM"},
            { "2ННК_BZ1", "NRF1"},
            { "2ННК_BZ", "NCRF"},
            { "2ННК_MZ1", "NRN1"},
            { "2ННК_MZ", "NCRN"},
            { "2ННК - Кн", "NCPR"},
            { "НГК_Uhv", "NGHV"},
            { "НГК_Upd_ngk", "NGPD"},
            { "НГК_T", "NGTM"},
            { "НГК_ngk1", "NGC"},
            { "НГК_ngk", "NGUE"},
            { "НГК - Кн", "NGPR"},
            { "SP_SUM", "SPSM"},
            { "SP", "SP"},
            { "combi_sp_sum1", "SPS1"},
            { "combi_sp_sum2", "SPS2"},
            { "combi_sp_sum3", "SPS3"},
            { "ГКС - Сумма общ", "GRSR"},
            { "ГКС_ШИМ_Авто", "PWMA"},
            { "ГКС_ШИМ_Ручн", "PWMH"},
            { "ГКС_Т", "GRST"},
            { "ГКС_T_rtd", "GRTD"},
            { "ГКС_Калий", "GPOT"},
            { "ГКС_Уран", "GURA"},
            { "ГКС_Торий", "GTOR"},
            { "ГКС-ГК_мкР", "GRS"},
            { "ГКС_Сумма1", "GSU1"},
            { "ГКС_Сумма2", "GSU2"},
            { "ГКС_Сумма3", "GSU3"},
            { "ГКС_Сумма4", "GSU4"},
            { "ГКС_Сумма5", "GSU5"},
            { "ГКС_Сумма6", "GSU6"},
            { "ГКС_Сумма15", "GSU15"},
            { "КУ ВЧ", "KUHV"},
            { "КУ НЧближн.", "KULN"},
            { "КУ НЧдальн.", "KULF"},
            { "КУ инт.", "KUIN"},
            { "МАК Визир", "VIZ"},
            { "МАК X проек. грав. поля", "GX"},
            { "МАК Y проек. грав. поля", "GY"},
            { "МАК Z проек. грав. поля", "GZ"},
            { "МАК Темпер.", "SKTM"},
            { "Прием ВЧСК", "RSHF"},
            { "Прием НЧСКближн.", "RLFN"},
            { "Прием НЧСКдальн.", "RLFF"},
            { "Прием ИНТ", "RINT"},
            { "ПриемСинхр1", "SYN1"},
            { "ПриемСинхр2", "SYN2"},
            { "ПриемСинхр3", "SYN3"},
            { "ПриемСинхр4", "SYN4"},
            { "HF1", "HF1"},
            { "HF2", "HF2"},
            { "HF3", "HF3"},
            { "HF4", "HF4"},
            { "HF5", "HF5"},
            { "HF6", "HF6"},
            { "HF7", "HF7"},
            { "HF8", "HF8"},
            { "LFN1", "LFN1"},
            { "LFN2", "LFN2"},
            { "LFN3", "LFN3"},
            { "LFN4", "LFN4"},
            { "LFN5", "LFN5"},
            { "LFN6", "LFN6"},
            { "LFN7", "LFN7"},
            { "LFN8", "LFN8"},
            { "LFF1", "LFF1"},
            { "LFF2", "LFF2"},
            { "LFF3", "LFF3"},
            { "LFF4", "LFF4"},
            { "LFF5", "LFF5"},
            { "LFF6", "LFF6"},
            { "LFF7", "LFF7"},
            { "LFF8", "LFF8"},
            { "W1", "W1"},
            { "W2", "W2"},
            { "МАК-100СК Режим передачи", "TRMO"},
            { "Parameters", "PARS"},
            { "Wave_parameters", "WPAR"},
            { "Wave5", "W5"},
            { "res_const1", "RC1"},
            { "res_const2", "RC2"},
            { "res_const3", "RC3"},
            { "res_const4", "RC4"},
            { "res_const5", "RC5"},
            { "res_const6", "RC6"},
            { "res_const7", "RC7"},
            { "res_const8", "RC8"},
            { "res_const9", "RC9"},
            { "res_const10", "RC10"},
            { "phase_const1", "PC1"},
            { "phase_const2", "PC2"},
            { "phase_const3", "PC3"},
            { "phase_const4", "PC4"},
            { "phase_const5", "PC5"},
            { "phase_const6", "PC6"},
            { "phase_const7", "PC7"},
            { "phase_const8", "PC8"},
            { "phase_const9", "PC9"},
            { "phase_const10", "PC10"},
            { "okno_const1", "OC1"},
            { "okno_const2", "OC2"},
            { "okno_const3", "OC3"},
            { "okno_const4", "OC4"},
            { "okno_const5", "OC5"},
            { "okno_const6", "OC6"},
            { "okno_const7", "OC7"},
            { "okno_const8", "OC8"},
            { "okno_const9", "OC9"},
            { "okno_const10", "OC10"},
            { "МАК-МП сер", "NUM"},
            { "МАК-МП напр", "VOLT"},
            { "МАК-МП Температура", "TEMP"},
            { "RecievingFlag_1", "RF1"},
            { "RecievingFlag_2", "RF2"},
            { "RecievingFlag_3", "RF3"},
            { "RecievingFlag_4", "RF4"},
            { "RecievingFlag_5", "RF5"},
            { "МАК-МП ИНКЛ Прием", "REIN"},
            { "ИНКЛ - ГК_HV", "GRHV"},
            { "ИНКЛ - ГК_PD", "GRPD"},
            { "ИНКЛ_ГК_имп", "GRC"},
            { "ИНКЛ_ГК_мкР", "GR"},
            { "ИНКЛ - ГК_timer", "GRTI"},
            { "ИНКЛ_Визир_магнитный", "VIZM"},
            { "mrb8", "MRB8"},
            { "az8", "AZ8"},
            { "ИНКЛ_Магнитное поле", "MPOL"},
            { "ИНКЛ_Грав. поле", "GPOL"},
            { "ИНКЛ_Темп. аксел.", "AXTM"},
            { "ИНКЛ_Темп. магнитом.", "MGTM"},
            { "ИНКЛ_X - проек. грав. поля", "XGP"},
            { "ИНКЛ_Y - проек. грав. поля", "YGP"},
            { "ИНКЛ_Z - проек. грав. поля", "ZGP"},
            { "ИНКЛ_X - проек. магн. поля", "XMP"},
            { "ИНКЛ_Y - проек. магн. поля", "YMP"},
            { "ИНКЛ_Z_проек. магн. поля", "ZMP"},
            { "ИНКЛ_X АЦП акселер.", "XAD"},
            { "ИНКЛ_Y АЦП акселер.", "YAD"},
            { "ИНКЛ_Z АЦП акселер.", "ZAD"},
            { "ИНКЛ_T АЦП акселер.", "TAD"},
            { "ИНКЛ_X АЦП магнитом.", "XADM"},
            { "ИНКЛ_Y АЦП магнитом.", "YADM"},
            { "ИНКЛ_Z АЦП магнитом.", "ZADM"},
            { "ИНКЛ_SerNumber_ГК", "GRSN"},
            { "ИНКЛ_SerNumber_ИНКЛ", "INSN"},
            { "XX1", "XX1"},
            { "XX2", "XX2"},
            { "XX3", "XX3"},
            { "XX4", "XX4"},
            { "XX5", "XX5"},
            { "XX6", "XX6"},
            { "XX7", "XX7"},
            { "XX8", "XX8"},
            { "XY1", "XY1"},
            { "XY2", "XY2"},
            { "XY3", "XY3"},
            { "XY4", "XY4"},
            { "XY5", "XY5"},
            { "XY6", "XY6"},
            { "XY7", "XY7"},
            { "XY8", "XY8"},
            { "YX1", "YX1"},
            { "YX2", "YX2"},
            { "YX3", "YX3"},
            { "YX4", "YX4"},
            { "YX5", "YX5"},
            { "YX6", "YX6"},
            { "YX7", "YX7"},
            { "YX8", "YX8"},
            { "YY1", "YY1"},
            { "YY2", "YY2"},
            { "YY3", "YY3"},
            { "YY4", "YY4"},
            { "YY5", "YY5"},
            { "YY6", "YY6"},
            { "YY7", "YY7"},
            { "YY8", "YY8"},
            { "WHF1", "WHF1"},
            { "WHF2", "WHF2"},
            { "WHF3", "WHF3"},
            { "WHF4", "WHF4"},
            { "WHF5", "WHF5"},
            { "WHF6", "WHF6"},
            { "WHF7", "WHF7"},
            { "WHF8", "WHF8"},
            { "WLF1", "WLF1"},
            { "WLF2", "WLF2"},
            { "WLF3", "WLF3"},
            { "WLF4", "WLF4"},
            { "WLF5", "WLF5"},
            { "WLF6", "WLF6"},
            { "WLF7", "WLF7"},
            { "WLF8", "WLF8"},
            { "RB8", "RB8"},
            { "МАК-МП Режим", "MODE"},
            { "wave_parameters", "PARS"},
            { "Wave 1", "W1"},
            { "Wave 2", "W2"},
            { "Wave 3", "W3"},
            { "Wave 4", "W4"},
            { "БМК_ Количество посылок", "CNT"},
            { "БМК_Напряжение на двигателе", "UMOT"},
            { "БМК_Напряжение питания", "SUVO"},
            { "БМК_Ток двигателя", "IMOT"},
            { "БМК_Температура", "TEMP"},
            { "БМК_Перенапряжение", "OVER"},
            { "БМК_КЗ", "CIRC"},
            { "МКВ", "CALI"},
            { "МБК", "MBK"},
            { "МПЗ", "MPZ"},
            { "МГЗ", "MGZ"},
            { "БМК_Радиус 1 (МК)", "RAD1"},
            { "БМК_Радиус 2 (БМК)", "RAD2"},
            { "БМК_Ue", "UE"},
            { "БМК_Ioc", "LOC"},
            { "БМК_Iof", "LOF"},
            { "БМК_Upz", "UPZ"},
            { "БМК_Ugz", "UGZ"},
            { "БМК_Imk", "LMK"},
            { "ПФ_ Количество посылок", "CNT"},
            { "ПФ_Напряжение на двигателе", "UMOT"},
            { "ПФ_Напряжение питания", "SUVO"},
            { "ПФ_Ток двигателя", "IMOT"},
            { "ПФ_Температура", "TEMP"},
            { "ПФ_Угол", "ANGL"},
            { "ПФ_Перенапряжение", "OVER"},
            { "ПФ_КЗ", "CIRC"},
            { "ПФ_R6", "R6"},
            { "ПФ_R5", "R5"},
            { "ПФ_R4", "R4"},
            { "ПФ_R3", "R3"},
            { "ПФ_R2", "R2"},
            { "ПФ_R1", "R1"},
            { "ПФ_D1", "D1"},
            { "ПФ_D2", "D2"},
            { "ПФ_D3", "D3"},
            { "ПФ_Dsr", "DSR"},
            { "ПФ_ Dokr1", "DOK1"},
            { "ПФ_ Dokr2", "DOK2"},
            { "ПФ_Dokr", "DOK"},
            { "ПФ_ Dsqrt", "DSQR"},
            { "V", "V"},
            { "WF1", "WF1"},
            { "N1", "N1"},
            { "VT1", "VT1"},
            { "WF2", "WF2"},
            { "N2", "N2"},
            { "VT2", "VT2"},
            { "WF3", "WF3"},
            { "N3", "N3"},
            { "VT3", "VT3"},
            { "W3", "W3"},
            { "WF4", "WF4"},
            { "N4", "N4"},
            { "VT4", "VT4"},
            { "W4", "W4"},
            { "WF5", "WF5"},
            { "N5", "N5"},
            { "VT5", "VT5"},
            { "W5", "W5"},
            { "WF6", "WF6"},
            { "N6", "N6"},
            { "VT6", "VT6"},
            { "W6", "W6"},
            { "WF7", "WF7"},
            { "N7", "N7"},
            { "VT7", "VT7"},
            { "W7", "W7"},
            { "WF8", "WF8"},
            { "N8", "N8"},
            { "VT8", "VT8"},
            { "W8", "W8"},
            { "WF9", "WF9"},
            { "N9", "N9"},
            { "VT9", "VT9"},
            { "W9", "W9"},
            { "WF10", "WF10"},
            { "N10", "N10"},
            { "VT10", "VT10"},
            { "W10", "W10"},
            { "WF11", "WF11"},
            { "N11", "N11"},
            { "VT11", "VT11"},
            { "W11", "W11"},
            { "SAP_X", "SAPX"},
            { "SAP_Y", "SAPY"},
            { "САП_Z", "SAPZ"},
            { "САП_U", "SAPU"},
            { "SAP_T", "SAPT"},
            { "САП_Угол", "ANGL"},
            { "САП _X", "SAPX"},
            { "САП _Y", "SAPY"},
            { "САП _Z", "SAPZ"},
            { "САП _U", "SAPU"},
            { "САП _T", "SAPT"},
            { "СГДТ-Номер", "NUM"},
            { "СГДТ-БЗ1", "L1CO"},
            { "СГДТ-БЗ1 уе", "L1UE"},
            { "СГДТ-БЗ2", "L2CO"},
            { "СГДТ-БЗ2 уе", "L2UE"},
            { "СГДТ-БЗ3", "L3CO"},
            { "СГДТ-БЗ3 уе", "L3UE"},
            { "СГДТ-БЗ4", "L4CO"},
            { "СГДТ-БЗ4 уе", "L4UE"},
            { "СГДТ-БЗ5", "L5CO"},
            { "СГДТ-БЗ5 уе", "L5UE"},
            { "СГДТ-БЗ6", "L6CO"},
            { "СГДТ-БЗ6 уе", "L6UE"},
            { "СГДТ-БЗ7", "L7CO"},
            { "СГДТ-БЗ7 уе", "L7UE"},
            { "СГДТ-БЗ8", "L8CO"},
            { "СГДТ-БЗ8 уе", "L8UE"},
            { "СГДТ-БЗ инт", "LIN"},
            { "СГДТ-БЗ инт уе", "LUE"},
            { "СГДТ-МЗ", "NCO"},
            { "СГДТ-МЗ уе", "NUE"},
            { "СГДТ-ГК", "GR"},
            { "СГДТ-Угол", "ANG"},
            { "СГДТ-Температура", "TEMP"},
            { "СГДТ-Напряжение зонда", "USON"},
            { "СГДТ-Счетчик 50мс", "CNT5"},
            { "СГДТ-Цикл. счетчик", "CNT"},
            { "ЦМ-Номер", "NUM"},
            { "ЦМ-БЗ1", "L1CO"},
            { "ЦМ-БЗ1 уе", "L1UE"},
            { "ЦМ-БЗ2", "L2CO"},
            { "ЦМ-БЗ2 уе", "L2UE"},
            { "ЦМ-БЗ3", "L3CO"},
            { "ЦМ-БЗ3 уе", "L3UE"},
            { "ЦМ-БЗ4", "L4CO"},
            { "ЦМ-БЗ4 уе", "L4UE"},
            { "ЦМ-БЗ5", "L5CO"},
            { "ЦМ-БЗ5 уе", "L5UE"},
            { "ЦМ-БЗ6", "L6CO"},
            { "ЦМ-БЗ6 уе", "L6UE"},
            { "ЦМ-БЗ7", "L7CO"},
            { "ЦМ-БЗ7 уе", "L7UE"},
            { "ЦМ-БЗ8", "L8CO"},
            { "ЦМ-БЗ8 уе", "L8UE"},
            { "ЦМ-БЗ инт", "LIN"},
            { "ЦМ-БЗ инт уе", "LUE"},
            { "ЦМ-МЗ", "NCO"},
            { "ЦМ-МЗ уе", "NUE"},
            { "ЦМ-ГК", "GR"},
            { "ЦМ-Угол", "ANG"},
            { "ЦМ-Температура", "TEMP"},
            { "ЦМ-Напряжение зонда", "USON"},
            { "ЦМ-Счетчик 50мс", "CNT5"},
            { "ЦМ-Цикл. счетчик", "CNT"},
            { "BatteryStatus", "BATS"},
            { "MasterSlaveStatus", "MSLS"},
            { "TelemetryExplorerStatus", "TEXS"},
            { "ExplorerPowerStatus", "EXPS"},
            { "cnt", "CNT"},
            { "axel_x", "A_X"},
            { "axel_y", "A_Y"},
            { "axel_z", "A_Z"},
            { "shock_x", "S_X"},
            { "shock_y", "S_Y"},
            { "shock_z", "S_Z"},
            { "RTC", "RTC"},
            { "i_зонда", "ISON"},
            { "u_зонда", "USON"},
            { "u_МБ", "UBAT"},
            { "u_ман", "UMAN"},
            { "st", "ST"},
            { "Сост флеш", "FLSH"},
            { "Запись", "REC"},
            { "Прием", "RECP"},
            { "SerialNumber", "NUM"},
            { "АК-64 КУ ВЧ", "AK1"},
            { "АК-64 Текущий КУ", "AK2"},
            { "АК-64 Визир", "AK3"},
            { "АК-64 X проек. грав. поля", "AK4"},
            { "АК-64 Y проек. грав. поля", "AK5"},
            { "АК-64 Z проек. грав. поля", "AK6"},
            { "АК-64 Темпер.", "AK7"},
            { "АК-64 Колонна", "AK8"},
            { "АК-64 Прием ВЧСК", "AK9"},
            { "АК-64 Прием НЧСКближн.", "AK10"},
            { "АК-64 Прием НЧСКдальн.", "AK11"},
            { "АК-64 Прием ИНТ", "AK12"},
            { "АК-64 ПриемСинхрВЧ", "AK13"},
            { "АК-64 ПриемСинхр2", "AK14"},
            { "АК-64 ПриемСинхр3", "AK15"},
            { "АК-64 ПриемСинхрИНТ", "AK16"},


        };

        public static string Get4SymbolName(string curveName,string[] CreatedNames)
        {
            string @return = curveName;

            if (LISMnemonics.ContainsKey(curveName) != false)
            {
                @return = LISMnemonics[curveName];
            }
            else
            {
                string buffer = string.Empty;
                if (NameHasPostfix(@return))
                {
                    bool parseResult = int.TryParse(@return[@return.IndexOf('(') - 1].ToString(), out var number);
                    if (parseResult == true)
                        buffer += number.ToString();
                    parseResult = int.TryParse(@return[@return.IndexOf('(') + 1].ToString(), out number);
                    if (parseResult == true)
                        buffer += number.ToString();
                }
                else
                {
                    bool parseResult = int.TryParse(@return[@return.Length - 1].ToString(), out var number);
                    if (parseResult == true)
                        buffer += number.ToString();
                }
                if(4-buffer.Length < @return.Length)
                    @return = @return.Substring(0,4 - buffer.Length) + buffer;
                else @return = @return + buffer;
            }
            int cnt = 1;
            while(CreatedNames.Contains(@return))
            {
                @return = @return.Substring(0, 4 - cnt.ToString().Length) + cnt.ToString();
                ++cnt;
            }
            return @return;
        }

        private static bool NameHasPostfix(string name)
        {
            if (name.Contains('(') && name.Contains(')'))
                return true;
            else return false;
        }
    }
}
